### ISSUE TITLE
code's problems

### ISSUE THREAD

**Issue by yaozhibo** [naver/posebert#2]
First I got the following issue,
```
Traceback (most recent call last):
  File "demo.py", line 313, in <module>
    main(args.video, args.method, args.sideview == 1)
  File "demo.py", line 122, in main
    dets, indices, bestcls = DOPE_NMS(results[part+'_scores'], results['boxes'], results[part+'_pose2d'], results[part+'_pose3d'], min_score=0.3)
ValueError: not enough values to unpack (expected 3, got 2)
```
then, I delete `bestcls`. And I got the following issue,
```
Traceback (most recent call last):
  File "demo.py", line 313, in <module>
    main(args.video, args.method, args.sideview == 1)
  File "demo.py", line 125, in main
    dets = {k: v.float().data.cpu().numpy() for k,v in dets.items()}
AttributeError: 'Tensor' object has no attribute 'items'
```

**Comment by Kirstihly** [comment]
I guess you need to change the video input. Usually using a higher-resolution video will solve the problem. The issue is caused by returning empty tensors [L324](https://github.com/naver/posebert/blob/master/dope.py#L324) and [L328](https://github.com/naver/posebert/blob/master/dope.py#L328). When the score is low, it will return empty tensors. But the later process needs a dictionary of ```score```, ```pose2d```, and ```pose3d``` as returned here: [L336](https://github.com/naver/posebert/blob/master/dope.py#L336)

**Comment by yaozhibo** [comment]
I have implemented training code, could you help me to check the reason why I get a bad result

**Comment by Qusong1** [comment]
> I have implemented training code, could you help me to check the reason why I get a bad result

Hello, i also want to train the posebert, i will appeciate it if you shareing the training code with me! Thank you very much!

**Comment by Qusong1** [comment]
> I have implemented training code, could you help me to check the reason why I get a bad result

hello, could you tell me your email? i really need this training code, thank you very much!
